In [39]:
 #series学习
import pandas as pd
s = pd.Series([1,2,3])
print(s)
#自定义索引
s = pd.Series([1,2,3,4,5], index = ['a','b','c','d','e'])
#定义name
s = pd.Series([1,2,3,4,5], index = ['A','B','c','d','e'],name = '月份')
print(s)

0    1
1    2
2    3
dtype: int64
A    1
B    2
c    3
d    4
e    5
Name: 月份, dtype: int64

In [43]:
#通过字典来创建
s = pd.Series({'a':1,'b':2,'c':3,'d':4})
print(s)
s1 = pd.Series(s,index=['a','c'])
print(s1)

a    1
b    2
c    3
d    4
dtype: int64
a    1
c    3
dtype: int64

In [ ]:
#series的属性
'index:Series的索引对象'
'values:Series的值'
'dtype or dtypes:Series的元素类型'
'shape:Series的形状'
'ndim:Series的维度'
'size:Series的元素个数'
'name:Series的名称'
'loc[] 显式索引，按标签索引或切片'
'iloc[] 隐式索引，按位置索引或切片'
'at[] 使用标签访问单个元素'
'iat[] 使用位置访问单个元素'

In [48]:
#print(s.index)
#print(s.values)
#print(s.shape,s.ndim,s.size)
#s.name='test'
#print(s.dtype,s.name)
print(s.loc['b'])#显式索引 可切片
print(s.loc['a':'c'])
print(s.iloc[1])#隐式索引  可切片
print(s.iloc[0:2])
print(s.at['a']) #只能找到精确一个值，不能切片
print(s.iat[0])

2
a    1
b    2
c    3
dtype: int64
2
a    1
b    2
dtype: int64
1
1

In [63]:
#访问数据
#print(s['a'])
#print(s['b'])
#print(s['c'])
print(s)
print(s[s<3])#可以布尔索引
s['f'] = 5
s['g'] = 6
print(s.head(2))
print(s.tail(1))

a    1
b    2
c    3
d    4
f    5
g    6
dtype: int64
a    1
b    2
dtype: int64
a    1
b    2
dtype: int64
g    6
dtype: int64

In [67]:
#常见函数
import numpy as np
s = pd.Series([10,2,np.nan,None,3,4,5],index =['A','B','C','D','E','F','G'],name = 'data')
print(s)

A    10.0
B     2.0
C     NaN
D     NaN
E     3.0
F     4.0
G     5.0
Name: data, dtype: float64

In [71]:
s.head()#默认取前5行的数据
s.tail()#默认取后5行的数据

C    NaN
D    NaN
E    3.0
F    4.0
G    5.0
Name: data, dtype: float64

In [72]:
#查看所有描述性信息
s.describe()

count     5.000000
mean      4.800000
std       3.114482
min       2.000000
25%       3.000000
50%       4.000000
75%       5.000000
max      10.000000
Name: data, dtype: float64

In [73]:
#获取元素个数
print(s.count())#忽略缺失值

5

In [76]:
#获取索引
print(s.keys()) #方法
print(s.index) #属性

Index(['A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='str')
Index(['A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='str')

In [79]:
print(s.isna())
s.isna()

A    False
B    False
C     True
D     True
E    False
F    False
G    False
Name: data, dtype: bool

A    False
B    False
C     True
D     True
E    False
F    False
G    False
Name: data, dtype: bool

In [83]:
s.isin([10,2,5]) #检查每个元素是否在参数集合中

A     True
B     True
C    False
D    False
E    False
F    False
G     True
Name: data, dtype: bool

In [84]:
s.describe()

count     5.000000
mean      4.800000
std       3.114482
min       2.000000
25%       3.000000
50%       4.000000
75%       5.000000
max      10.000000
Name: data, dtype: float64

In [90]:
print(s.mean()) #平均值
print(s.std()) #标准差
print(s.var()) #方差
print(s.sum()) #总和
print(s.min()) #最小值
print(s.max()) #最大值
print(s.median()) #中位数

4.8
3.1144823004794877
9.700000000000001
24.0
2.0
10.0
4.0

In [96]:
print(s.sort_values())
print(s.quantile(0.75)) #分位数

B     2.0
E     3.0
F     4.0
G     5.0
A    10.0
C     NaN
D     NaN
Name: data, dtype: float64
5.0

In [98]:
#众数
s['H'] = 4
print(s.mode())

0    4.0
Name: data, dtype: float64

In [99]:
print(s.value_counts()) #每个元素的计数

data
4.0     2
10.0    1
2.0     1
3.0     1
5.0     1
Name: count, dtype: int64

In [103]:
s.drop_duplicates()#去重
s.unique()#去重，但返回类型不同
print(s.nunique()) #去重后的元素个数

5

In [104]:
#排序  值、索引
s.sort_index() #按索引排序
s.sort_values() #按值排序

A    10.0
B     2.0
C     NaN
D     NaN
E     3.0
F     4.0
G     5.0
H     4.0
Name: data, dtype: float64

# DataFrame

In [12]:
# dataframe的创建方式
import pandas as pd
import numpy as np
#通过series来创建
s1 = pd.Series([1,2,3,4,5])
s2 = pd.Series([6,7,8,9,10])
df = pd.DataFrame({'第1列':s1,'第2列':s2})
# 通过字典来创建
df = pd.DataFrame(
    {
      'name':['tom','jack','alice','bob','allen'],
       'age':[15,17,20,26,30],
        'score':[60.5,80,30,70.888,86]
    },index = [1,2,3,4,5],columns = ['name','score','age']#列标签
)
df

    name   score  age
1    tom  60.500   15
2   jack  80.000   17
3  alice  30.000   20
4    bob  70.888   26
5  allen  86.000   30

In [14]:
# dataframe的属性
print('行索引：')
print(df.index)
print('列标签：')
print(df.columns)
print('值')
print(df.values)

行索引：
Index([1, 2, 3, 4, 5], dtype='int64')
列标签：
Index(['name', 'score', 'age'], dtype='str')
值
[['tom' 60.5 15]
 ['jack' 80.0 17]
 ['alice' 30.0 20]
 ['bob' 70.888 26]
 ['allen' 86.0 30]]

In [19]:
print('维度：',df.ndim)
print('形状',df.shape)
print('元素个数',df.size)
print('数据类型')
print(df.dtypes)

维度： 2
形状 (5, 3)
元素个数 15
数据类型
name         str
score    float64
age        int64
dtype: object

In [25]:
# 行列转置
print(df.T)
print(df.T.index)
print(df.T.columns)
df

          1     2      3       4      5
name    tom  jack  alice     bob  allen
score  60.5  80.0   30.0  70.888   86.0
age      15    17     20      26     30
Index(['name', 'score', 'age'], dtype='str')
Index([1, 2, 3, 4, 5], dtype='int64')

    name   score  age
1    tom  60.500   15
2   jack  80.000   17
3  alice  30.000   20
4    bob  70.888   26
5  allen  86.000   30

In [28]:
#获取元素 loc iloc at iat
#获取某行的元素
print(df.loc[4])#显式索引，按index索引
print(df.iloc[3])#隐式索引，按自带的索引

name        bob
score    70.888
age          26
Name: 4, dtype: object
name        bob
score    70.888
age          26
Name: 4, dtype: object

In [32]:
#获取某列数据
print(df.loc[:,'name'])
print(df.iloc[:,0])

1      tom
2     jack
3    alice
4      bob
5    allen
Name: name, dtype: str
1      tom
2     jack
3    alice
4      bob
5    allen
Name: name, dtype: str

In [36]:
#获取单个元素
print(df.at[3,'name'])
print(df.iat[2,1])
print(df.loc[3,'name'])
print(df.iloc[2,1])

alice
30.0
alice
30.0

In [40]:
# 获取单列数据
print(df['name'])
print(df.name)
print(df[['name']])
df[['name']]

1      tom
2     jack
3    alice
4      bob
5    allen
Name: name, dtype: str
1      tom
2     jack
3    alice
4      bob
5    allen
Name: name, dtype: str
    name
1    tom
2   jack
3  alice
4    bob
5  allen

    name
1    tom
2   jack
3  alice
4    bob
5  allen

In [42]:
print(df[['name','age']]) #多列数据的获取

    name  age
1    tom   15
2   jack   17
3  alice   20
4    bob   26
5  allen   30

In [44]:
# 查看部分数据
print(df.head())
print(df.head(2))
print(df.tail())
print(df.tail(2))

    name   score  age
1    tom  60.500   15
2   jack  80.000   17
3  alice  30.000   20
4    bob  70.888   26
5  allen  86.000   30
   name  score  age
1   tom   60.5   15
2  jack   80.0   17
    name   score  age
1    tom  60.500   15
2   jack  80.000   17
3  alice  30.000   20
4    bob  70.888   26
5  allen  86.000   30
    name   score  age
4    bob  70.888   26
5  allen  86.000   30

In [57]:
#布尔索引筛选
#df[df.score>70] #单个条件
#df[(df.score>70)&(df.age<20)]
df[(df.score>70)|(df['age']<20)]

    name   score  age
1    tom  60.500   15
2   jack  80.000   17
4    bob  70.888   26
5  allen  86.000   30

In [61]:
#随机抽样
df.sample()
df.sample(3)

    name   score  age
2   jack  80.000   17
5  allen  86.000   30
4    bob  70.888   26

In [79]:
#常用方法
df = pd.DataFrame(
    {
      'name':['tom','jack','alice','bob','allen'],
       'age':[15,17,20,26,30],
        'score':[60.5,80,30.6,70.,83.5]
    },index = [1,2,3,4,5],columns = ['name','score','age']#列标签
)

In [64]:
print(df.head()) #查看前n行数据，默认是5行
print(df.tail(1))

    name  score  age
1    tom   60.5   15
2   jack   80.0   17
3  alice   30.6   20
4    bob   70.0   26
5  allen   83.5   30
    name  score  age
5  allen   83.5   30

In [66]:
print(df.isin(['jack',20])) #查看元素是否包含在参数集合中

    name  score    age
1  False  False  False
2   True  False  False
3  False  False   True
4  False  False  False
5  False  False  False

In [67]:
print(df.isna()) #查看元素是否是缺失值

    name  score    age
1  False  False  False
2  False  False  False
3  False  False  False
4  False  False  False
5  False  False  False

In [80]:
print(df['score'].sum()) #某一列的总和
print(df.score.max()) #最大值
print(df.score.min()) #最小值
print(df.score.mean()) #平均数
print(df.score.median()) #中位数
print(df.score.mode()) #众数

324.6
83.5
30.6
64.92
70.0
0    30.6
1    60.5
2    70.0
3    80.0
4    83.5
Name: score, dtype: float64

In [81]:
print(df.score.std()) #标准差
print(df.score.var()) #方差
print(df.score.quantile(0.25))

21.188605428390044
448.957
60.5

In [82]:
print(df.describe())

           score        age
count   5.000000   5.000000
mean   64.920000  21.600000
std    21.188605   6.268971
min    30.600000  15.000000
25%    60.500000  17.000000
50%    70.000000  20.000000
75%    80.000000  26.000000
max    83.500000  30.000000

In [83]:
print(df.count()) #返回每一列非缺失值的个数

name     5
score    5
age      5
dtype: int64

In [85]:
print(df.value_counts())#出现的次数

name   score  age
tom    60.5   15     1
jack   80.0   17     1
alice  30.6   20     1
bob    70.0   26     1
allen  83.5   30     1
Name: count, dtype: int64

In [86]:
print(df.drop_duplicates())#去重

    name  score  age
1    tom   60.5   15
2   jack   80.0   17
3  alice   30.6   20
4    bob   70.0   26
5  allen   83.5   30

In [88]:
print(df.duplicated())#查重
print(df.duplicated(subset = ['age']))#指定查重

1    False
2    False
3    False
4    False
5    False
dtype: bool
1    False
2    False
3    False
4    False
5    False
dtype: bool

In [89]:
print(df.replace(15,30))

    name  score  age
1    tom   60.5   30
2   jack   80.0   17
3  alice   30.6   20
4    bob   70.0   26
5  allen   83.5   30

In [98]:
df.cumsum()
df.cummax()
df.cummin(axis=0)

    name  score  age
1    tom   60.5   15
2   jack   60.5   15
3  alice   30.6   15
4  alice   30.6   15
5  alice   30.6   15

In [100]:
print(df.sort_index()) #按行索引升序排列
print(df.sort_index(ascending = False)) #按行索引降序排列

    name  score  age
1    tom   60.5   15
2   jack   80.0   17
3  alice   30.6   20
4    bob   70.0   26
5  allen   83.5   30
    name  score  age
5  allen   83.5   30
4    bob   70.0   26
3  alice   30.6   20
2   jack   80.0   17
1    tom   60.5   15

In [101]:
print(df.sort_values(by='name')) #按姓名列的值升序排列

    name  score  age
3  alice   30.6   20
5  allen   83.5   30
4    bob   70.0   26
2   jack   80.0   17
1    tom   60.5   15

In [104]:
print(df.sort_values(by='score',ascending=False))

    name  score  age
5  allen   83.5   30
2   jack   80.0   17
4    bob   70.0   26
1    tom   60.5   15
3  alice   30.6   20

In [108]:
print(df.sort_values(by=['score','age']))

    name  score  age
3  alice   30.6   20
1    tom   60.5   15
4    bob   70.0   26
2   jack   80.0   17
5  allen   83.5   30

In [109]:
print(df.sort_values(by=['score','age'],ascending =[True,False]))

    name  score  age
3  alice   30.6   20
1    tom   60.5   15
4    bob   70.0   26
2   jack   80.0   17
5  allen   83.5   30

In [112]:
df.nlargest(2,columns =['score','age']) #取最大的2行
df.nsmallest(2,columns =['score','age']) #取最小的2行

    name  score  age
3  alice   30.6   20
1    tom   60.5   15

# 数据的导入导出

In [4]:
#数据的导入
import pandas as pd
df = pd.read_csv('data/employees.csv')
print(type(df))
print(df.tail())
print(df.salary.mean())

<class 'pandas.DataFrame'>
     employee_id first_name last_name     email  phone_number      job_id  \
102          202        Pat       Fay      PFAY  603.123.6666      MK_REP
103          203      Susan    Mavris   SMAVRIS  515.123.7777      HR_REP
104          204    Hermann      Baer     HBAER  515.123.8888      PR_REP
105          205    Shelley   Higgins  SHIGGINS  515.123.8080      AC_MGR
106          206    William     Gietz    WGIETZ  515.123.8181  AC_ACCOUNT

      salary  commission_pct  manager_id  department_id
102   6000.0             NaN       201.0           20.0
103   6500.0             NaN       101.0           40.0
104  10000.0             NaN       101.0           70.0
105  12000.0             NaN       101.0          110.0
106   8300.0             NaN       205.0          110.0
6461.682242990654

In [6]:
#数据的导出
df = df.tail()
df.to_csv('data/new.csv')

In [16]:
#json
df = pd.read_json('data/test.json')
print(type(df))

import json
with open('data/test.json',encoding='utf-8') as f:
    data = json.load(f)
#print(data)
print(type(data))
df = pd.DataFrame(data['users'])
print(type(df))
df

<class 'pandas.DataFrame'>
<class 'dict'>
<class 'pandas.DataFrame'>

   id name  age                 email  is_active   join_date
0   1   张三   28  zhangsan@example.com       True  2022-03-15
1   2   李四   35      lisi@example.com      False  2021-11-02
2   3   王五   24    wangwu@example.com       True  2023-01-20

In [36]:
#缺失值的处理
import pandas as pd
import numpy as np
s = pd.Series([1,2,np.nan,None,pd.NA])
df= pd.DataFrame([[1,pd.NA,2],[2,3,5],[None,4,6]],columns = ['第1列','第2列','第3列'])
print(s),
#查看是否是缺失值
#print(s.isna())
#print(s.isnull())
#print(df.isna())
print(df.isnull())
print(df.isna().sum(axis = 1))
print(s.isna().sum()) #查看缺失值的个数

0       1
1       2
2     NaN
3    None
4    <NA>
dtype: object
     第1列    第2列    第3列
0  False   True  False
1  False  False  False
2   True  False  False
0    1
1    0
2    1
dtype: int64
3

In [49]:
#剔除缺失值
print(s.dropna())
print('-'*30)
print(df)
print(df.dropna())#剔除一整条的记录
print(df.dropna(how='all')) #如果所有的值都是缺失值，删除这一行
print(df.dropna(thresh=1)) #如果至少有n个值不是缺失值，就保留
print(df.dropna(axis = 1)) #剔除一整列的记录
print(df.dropna(subset = ['第1列'])) #如果某列有缺失值，则删除这一行

0    1
1    2
dtype: object
------------------------------
   第1列   第2列  第3列
0  1.0  <NA>    2
1  2.0     3    5
2  NaN     4    6
   第1列 第2列  第3列
1  2.0   3    5
   第1列   第2列  第3列
0  1.0  <NA>    2
1  2.0     3    5
2  NaN     4    6
   第1列   第2列  第3列
0  1.0  <NA>    2
1  2.0     3    5
2  NaN     4    6
   第3列
0    2
1    5
2    6
   第1列   第2列  第3列
0  1.0  <NA>    2
1  2.0     3    5

In [64]:
#填充缺失值
df = pd.read_csv('data/weather_withna.csv')
df.tail()
df.isna().sum(axis = 0)
df.head()
print(df.fillna({'temp_max':20,'wind':2.5}).tail()) #使用字典来填充
print(df.fillna(df[['temp_max','wind']].mean()).tail()) #使用统计值来填充
print(df.ffill().tail())#用前面的相邻值填充
print(df.bfill().tail())#用后面的相邻值填充

            date  precipitation  temp_max  temp_min  wind weather
1456  2015-12-27            NaN      20.0       NaN   2.5     NaN
1457  2015-12-28            NaN      20.0       NaN   2.5     NaN
1458  2015-12-29            NaN      20.0       NaN   2.5     NaN
1459  2015-12-30            NaN      20.0       NaN   2.5     NaN
1460  2015-12-31           20.6      12.2       5.0   3.8    rain
            date  precipitation   temp_max  temp_min      wind weather
1456  2015-12-27            NaN  15.851468       NaN  3.242055     NaN
1457  2015-12-28            NaN  15.851468       NaN  3.242055     NaN
1458  2015-12-29            NaN  15.851468       NaN  3.242055     NaN
1459  2015-12-30            NaN  15.851468       NaN  3.242055     NaN
1460  2015-12-31           20.6  12.200000       5.0  3.800000    rain
            date  precipitation  temp_max  temp_min  wind weather
1456  2015-12-27            0.0      11.1       4.4   4.8     sun
1457  2015-12-28            0.0      11.1       4.4   4.8     sun
1458  2015-12-29            0.0      11.1       4.4   4.8     sun
1459  2015-12-30            0.0      11.1       4.4   4.8     sun
1460  2015-12-31           20.6      12.2       5.0   3.8    rain
            date  precipitation  temp_max  temp_min  wind weather
1456  2015-12-27           20.6      12.2       5.0   3.8    rain
1457  2015-12-28           20.6      12.2       5.0   3.8    rain
1458  2015-12-29           20.6      12.2       5.0   3.8    rain
1459  2015-12-30           20.6      12.2       5.0   3.8    rain
1460  2015-12-31           20.6      12.2       5.0   3.8    rain

# 数据转换

In [72]:
import pandas as pd
data ={
    'name':['alice','alice','bob','alice','jack','bob'],
    'age':[26,25,30,25,35,30],
    'city':['NY','NY','LA','NY','SF','LA']
}
df = pd.DataFrame(data)
df.duplicated()#一整条记录都是一样的，标记为重复，返回True
df.drop_duplicates(subset=['name'])#根据指定列去重
df.drop_duplicates(subset=['name'],keep = 'last')#保留最后一次出现的行
#print(df)
#print(df.duplicated())
#print(df.drop_duplicates())

    name  age city
0  alice   26   NY
2    bob   30   LA
4   jack   35   SF

In [74]:
#数据类型的转换
df = pd.read_csv('data/sleep.csv')
df.dtypes

person_id                    int64
gender                         str
age                          int64
occupation                     str
sleep_duration             float64
sleep_quality              float64
physical_activity_level      int64
stress_level                 int64
bmi_category                   str
blood_pressure                 str
heart_rate                   int64
daily_steps                  int64
sleep_disorder                 str
dtype: object

In [78]:
df['age'] = df['age'].astype('int16')
df.gender

0        Male
1      Female
2        Male
3        Male
4        Male
        ...
395    Female
396    Female
397    Female
398    Female
399      Male
Name: gender, Length: 400, dtype: str

In [86]:
df['gender'] = df['gender'].astype('category')

In [87]:
df.gender

0        Male
1      Female
2        Male
3        Male
4        Male
        ...
395    Female
396    Female
397    Female
398    Female
399      Male
Name: gender, Length: 400, dtype: category
Categories (2, str): ['Female', 'Male']

In [89]:
df['is_male'] = df['gender'].map({'Female':True,'Male':False})
df.is_male

0      False
1       True
2      False
3      False
4      False
       ...
395     True
396     True
397     True
398     True
399    False
Name: is_male, Length: 400, dtype: category
Categories (2, bool): [True, False]

# 时间数据的处理

In [14]:
import pandas as pd
d = pd.Timestamp('2015-02-28 10:22')
d1 = pd.Timestamp('2015-02-28 13:22')
#属性
print(d)
print(type(d))
print('年：',d.year)
print('月:',d.month)
print('日:',d.day)
print(d.hour,d.minute,d.second)
print('季度：',d.quarter)
print('是否是月底：',d.is_month_end)
#方法
print('星期几：',d.day_name())
print('转换为天：',d.to_period('D'))
print('转换为季度：',d1.to_period('Q'))
print('转换为季度：',d1.to_period('Y'))
print('转换为季度：',d1.to_period('M'))
print('转换为周维度：',d1.to_period('W'))

2015-02-28 10:22:00
<class 'pandas.Timestamp'>
年： 2015
月: 2
日: 28
10 22 0
季度： 1
是否是月底： True
星期几： Saturday
转换为天： 2015-02-28
转换为季度： 2015Q1
转换为季度： 2015
转换为季度： 2015-02
转换为周维度： 2015-02-23/2015-03-01

In [17]:
#字符串转换为日期类型
a = pd.to_datetime('2015-02-28 10:22')
print(a)
print(type(a))
print(a.day_name())

2015-02-28 10:22:00
<class 'pandas.Timestamp'>
Saturday

In [28]:
#dataframes 日期转换
df = pd.DataFrame({
    'sale':[100,200,300],
    'date':['20250601','20250602','20250603']
})
df['datetime'] = pd.to_datetime(df['date'])
df
print(df.info())
df['week'] = df['datetime'].dt.day_name()#一整列日期用dt.
df['datetime'].dt.year

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   sale      3 non-null      int64
 1   date      3 non-null      str
 2   datetime  3 non-null      datetime64[us]
dtypes: datetime64[us](1), int64(1), str(1)
memory usage: 204.0 bytes
None

0    2025
1    2025
2    2025
Name: datetime, dtype: int32

In [33]:
#csv日期转换
df = pd.read_csv('data/weather.csv')
df['datetime'] = pd.to_datetime(df['date'])
df['datetime'].dt.day_name()

0          Sunday
1          Monday
2         Tuesday
3       Wednesday
4        Thursday
          ...
1456       Sunday
1457       Monday
1458      Tuesday
1459    Wednesday
1460     Thursday
Name: datetime, Length: 1461, dtype: str

In [56]:
df = pd.read_csv('data/weather.csv',parse_dates = ['date'])
df.info()
df['date'].dt.day_name()

<class 'pandas.DataFrame'>
RangeIndex: 1461 entries, 0 to 1460
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           1461 non-null   datetime64[us]
 1   precipitation  1461 non-null   float64
 2   temp_max       1461 non-null   float64
 3   temp_min       1461 non-null   float64
 4   wind           1461 non-null   float64
 5   weather        1461 non-null   str
dtypes: datetime64[us](1), float64(4), str(1)
memory usage: 68.6 KB

0          Sunday
1          Monday
2         Tuesday
3       Wednesday
4        Thursday
          ...
1456       Sunday
1457       Monday
1458      Tuesday
1459    Wednesday
1460     Thursday
Name: date, Length: 1461, dtype: str

In [57]:
#日期数据作为索引
df.set_index('date',inplace = True )
print(df.loc['2013-01':'2013-02'])

            precipitation  temp_max  temp_min  wind  weather
date
2013-01-01            0.0       5.0      -2.8   2.7      sun
2013-01-02            0.0       6.1      -1.1   3.2      sun
2013-01-03            4.1       6.7      -1.7   3.0     rain
2013-01-04            2.5      10.0       2.2   2.8     rain
2013-01-05            3.0       6.7       4.4   3.1     rain
2013-01-06            2.0       7.2       2.8   3.0     rain
2013-01-07            2.3      10.0       4.4   7.3     rain
2013-01-08           16.3      11.7       5.6   6.3     rain
2013-01-09           38.4      10.0       1.7   5.1     rain
2013-01-10            0.3       3.3      -0.6   2.1     snow
2013-01-11            0.0       2.8      -2.8   1.9  drizzle
2013-01-12            0.0       2.8      -3.9   2.0      sun
2013-01-13            0.0       2.2      -4.4   1.5      sun
2013-01-14            0.0       3.3      -2.2   1.3      sun
2013-01-15            0.0       6.7      -0.6   2.3      sun
2013-01-16            0.0       6.1      -3.9   1.8  drizzle
2013-01-17            0.0       3.9      -2.8   1.0  drizzle
2013-01-18            0.0       3.3      -1.1   1.3  drizzle
2013-01-19            0.0       1.1      -0.6   1.9  drizzle
2013-01-20            0.0       3.3      -0.6   2.1  drizzle
2013-01-21            0.0       2.2      -1.7   1.1  drizzle
2013-01-22            0.0       3.3      -1.7   0.6  drizzle
2013-01-23            5.1       7.2       2.2   3.1     rain
2013-01-24            5.8       7.2       1.1   2.6     rain
2013-01-25            3.0      10.6       2.8   2.1     rain
2013-01-26            2.3       8.3       3.9   4.5     rain
2013-01-27            1.8       5.6       3.9   4.5     rain
2013-01-28            7.9       6.1       3.3   3.2     rain
2013-01-29            4.3       8.3       5.0   3.9     rain
2013-01-30            3.6       8.9       6.7   3.9     rain
2013-01-31            3.0       9.4       7.2   4.0     rain
2013-02-01            0.3      11.7       5.0   2.9     rain
2013-02-02            0.0       6.1       2.8   2.0  drizzle
2013-02-03            2.3       8.9       2.8   2.9     rain
2013-02-04            0.0      10.6       6.7   2.6     rain
2013-02-05            3.3      10.0       6.7   5.1     rain
2013-02-06            1.0      10.6       6.1   4.5     rain
2013-02-07            1.3       9.4       3.3   4.1     rain
2013-02-08            0.0       7.8       2.2   1.3      sun
2013-02-09            0.3       8.3       4.4   1.3     rain
2013-02-10            0.0       8.9       1.7   2.0  drizzle
2013-02-11            0.3       8.3       4.4   1.4     rain
2013-02-12            1.0      11.1       7.2   5.6     rain
2013-02-13            2.3       9.4       7.2   4.1     rain
2013-02-14            1.0       9.4       5.6   2.2     rain
2013-02-15            0.0      13.3       5.0   2.4  drizzle
2013-02-16            0.0      11.1       3.9   5.6     rain
2013-02-17            0.0       9.4       4.4   3.4     rain
2013-02-18            0.0       7.8       3.9   1.9     rain
2013-02-19            0.0      10.6       1.7   3.4      sun
2013-02-20            1.5       7.8       1.1   2.1     rain
2013-02-21            0.5       6.7       3.9   6.2     rain
2013-02-22            9.4       7.8       3.9   8.1     rain
2013-02-23            0.3      10.0       3.9   4.6     rain
2013-02-24            0.0       8.9       5.0   5.5     rain
2013-02-25            2.3      10.6       3.3   7.1     rain
2013-02-26            0.5       8.9       3.9   3.8     rain
2013-02-27            4.6      10.0       4.4   1.8     rain
2013-02-28            8.1      11.7       6.7   3.8     rain

In [60]:
#时间间隔
d1 = pd.Timestamp('2013-01-15')
d2 = pd.Timestamp('2023-02-23')
d3 = d2-d1
print(type(d3))
print(d3)

<class 'pandas.Timedelta'>
3691 days 00:00:00

In [63]:
df = pd.read_csv('data/weather.csv',parse_dates = ['date'])
df.info()
df['delta'] = df['date'] - df['date'][0]
df.set_index('delta',inplace = True)

<class 'pandas.DataFrame'>
RangeIndex: 1461 entries, 0 to 1460
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           1461 non-null   datetime64[us]
 1   precipitation  1461 non-null   float64
 2   temp_max       1461 non-null   float64
 3   temp_min       1461 non-null   float64
 4   wind           1461 non-null   float64
 5   weather        1461 non-null   str
dtypes: datetime64[us](1), float64(4), str(1)
memory usage: 68.6 KB

In [65]:
df
print(df.loc['10 days':'20 days'])

              date  precipitation  temp_max  temp_min  wind weather
delta
10 days 2012-01-11            0.0       6.1      -1.1   5.1     sun
11 days 2012-01-12            0.0       6.1      -1.7   1.9     sun
12 days 2012-01-13            0.0       5.0      -2.8   1.3     sun
13 days 2012-01-14            4.1       4.4       0.6   5.3    snow
14 days 2012-01-15            5.3       1.1      -3.3   3.2    snow
15 days 2012-01-16            2.5       1.7      -2.8   5.0    snow
16 days 2012-01-17            8.1       3.3       0.0   5.6    snow
17 days 2012-01-18           19.8       0.0      -2.8   5.0    snow
18 days 2012-01-19           15.2      -1.1      -2.8   1.6    snow
19 days 2012-01-20           13.5       7.2      -1.1   2.3    snow
20 days 2012-01-21            3.0       8.3       3.3   8.2    rain

In [74]:
days = pd.date_range('2025-07-03','2026-02-09',freq='ME')
#days = pd.date_range('2025-07-03',periods = 10,freq='YS')
print(days)

DatetimeIndex(['2025-07-31', '2025-08-31', '2025-09-30', '2025-10-31',
               '2025-11-30', '2025-12-31', '2026-01-31'],
              dtype='datetime64[us]', freq='ME')

In [77]:
df = pd.read_csv('data/weather.csv',parse_dates = ['date'])
#重新采样
df.set_index('date',inplace = True)
df[['temp_max','temp_min']].resample('YS').mean()

             temp_max  temp_min
date
2012-01-01  15.276776  7.289617
2013-01-01  16.058904  8.153973
2014-01-01  16.995890  8.662466
2015-01-01  17.427945  8.835616

# 分组聚合

In [105]:
#df.groupby('分组的字段')['聚合的字段']
import pandas as pd
df = pd.read_csv('data/employees.csv')
df = df.dropna(subset=['department_id'])
df['department_id'] = df['department_id'].astype('int64')
#计算不同部门平均薪资
df.groupby('department_id').groups #查看分组
df.groupby('department_id').get_group(20)#查看具体的某个分组数据
df2 = df.groupby('department_id')[['salary']].mean()
df2['salary'] = df2['salary'].round(2)
df2 = df2.reset_index()
df2.sort_values('salary',ascending = False)

    department_id    salary
8              90  19333.33
10            110  10150.00
6              70  10000.00
1              20   9500.00
7              80   8955.88
9             100   8600.00
3              40   6500.00
5              60   5760.00
0              10   4400.00
2              30   4150.00
4              50   3475.56

In [115]:
#计算不同部门不同岗位的人的平均薪资
df2 = df.groupby(['department_id','job_id'])[['salary']].mean()
df2=df2.reset_index()
df2['salary'] = df2['salary'].round(1)
df2.sort_values('salary',ascending = False)

    department_id      job_id   salary
13             90     AD_PRES  24000.0
14             90       AD_VP  17000.0
1              20      MK_MAN  13000.0
11             80      SA_MAN  12200.0
16            100      FI_MGR  12000.0
18            110      AC_MGR  12000.0
4              30      PU_MAN  11000.0
10             70      PR_REP  10000.0
12             80      SA_REP   8396.6
17            110  AC_ACCOUNT   8300.0
15            100  FI_ACCOUNT   7920.0
8              50      ST_MAN   7280.0
5              40      HR_REP   6500.0
2              20      MK_REP   6000.0
9              60     IT_PROG   5760.0
0              10     AD_ASST   4400.0
6              50    SH_CLERK   3215.0
7              50    ST_CLERK   2785.0
3              30    PU_CLERK   2780.0